### PR TITLE
Fixed branch name in git clone URL

### PR DESCRIPTION
**Pull request by ZeeWeasel**
Changed incorrect branch in url from 'godot-4.2.2-stable' to '4.2.2-stable'

### CODE REVIEW

**Review by Gramps — CHANGES_REQUESTED** [review]
Hey there!  [Actually, in godot-cpp, the tags do start with a `godot-` prefix; which is kinda weird.](https://github.com/godotengine/godot-cpp/tree/godot-4.2.2-stable)  That being said, you are on the right trail!  This edit actually needs to happen but with a different bit of text.

Instead of `godot-4.2.2-stable` this should be `4.1` as that version allows for the greatest compatibility for users.  If you can change it to that, then this will be fixed.

**Comment by Gramps** [comment]
Uh-oh, did we have the totally wrong git link?  Haha, oops.  Yeah, it should be `git@github.com:godotengine/godot-cpp.git`.  Also we don't want the `stable` tag but the actual `4.1` branch.  The stable is locked at 4.1 but the 4.1 branch keeps getting cherry-picked updates.

**Comment by ZeeWeasel** [comment]
Okay I think the last commit should do the trick ^^'

**Comment by Gramps** [comment]
Ayyy!  Thank you so much!  I wonder how many of our other cloning snippets are wrong, haha.

**Pull request merged**
